name: omnicast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  intl: any  # 由 flutter_localizations 固定版本
  lifecycle: ^0.2.0
  shared_preferences: ^2.3.5
  convert: ^3.1.2
  dio: ^5.7.0
  logger: ^2.5.0
  pointycastle: ^3.9.1
  ed25519_edwards: ^0.3.1
  bip39_mnemonic: ^4.0.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_smart_dialog: ^4.9.8
  styled_widget: ^0.4.1
  pretty_dio_logger: ^1.4.0
  getx_route_annotations: ^1.0.2
  local_auth: ^2.3.0
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  easy_refresh: ^3.4.0
  decimal: ^3.2.4
  rational: ^2.2.3
  flutter_secure_storage: ^9.2.4
  solana: ^0.32.0+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  getx_route_generator: ^1.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/img/
    - assets/svg/
flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
